# NODE SETTINGS
NODE_ID = 1

# SERVER SETTINGS
SERVER_HOST = "localhost"
SERVER_PORT = 8000

# PINS SETTINGS
DEVICES = [18,]  # Pins used

# NETWORK SETTINGS
STA_SSID = "YOUR SSID"
STA_PWD = "YOUR PASSWORD"
